# Generated by Django 4.1.13 on 2023-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('Activate', models.BooleanField(default=True)),
            ],
        ),
    ]
